"""
End-to-end chatbot with OpenAI + RAIL Score + Langfuse 3 observability.

Every turn is:
  1. Generated by OpenAI
  2. Evaluated by RAIL Score (8 dimensions)
  3. Logged to Langfuse with per-dimension scores attached to the trace

Requirements:
    pip install rail-score-sdk openai langfuse>=3.0

Usage:
    export OPENAI_API_KEY="sk-..."
    export RAIL_API_KEY="rail_..."
    export LANGFUSE_PUBLIC_KEY="pk-lf-..."
    export LANGFUSE_SECRET_KEY="sk-lf-..."
    python examples/chatbot_langfuse.py
"""

import asyncio
import os
import uuid

from openai import AsyncOpenAI

from rail_score_sdk import AsyncRAILClient
from rail_score_sdk.integrations import RAILLangfuse


RAIL_API_KEY = os.environ["RAIL_API_KEY"]
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]

MODEL = "gpt-4o-mini"
THRESHOLD = 7.0
SYSTEM_PROMPT = (
    "You are a helpful assistant for a healthcare platform. "
    "Always recommend consulting a doctor for medical decisions."
)


async def main():
    openai = AsyncOpenAI(api_key=OPENAI_API_KEY)

    # RAILLangfuse bridges RAIL scores into Langfuse traces.
    # It picks up LANGFUSE_PUBLIC_KEY / LANGFUSE_SECRET_KEY from env.
    rail_langfuse = RAILLangfuse(
        rail_api_key=RAIL_API_KEY,
        rail_mode="basic",
        rail_domain="healthcare",
        score_dimensions=True,      # push all 8 dimension scores
        score_prefix="rail_",       # scores named rail_overall, rail_safety, etc.
    )

    messages = [{"role": "system", "content": SYSTEM_PROMPT}]

    # One Langfuse session for the entire conversation
    session_id = f"chat-{uuid.uuid4().hex[:8]}"

    print("=" * 60)
    print("  OpenAI + RAIL + Langfuse Chatbot")
    print(f"  Model: {MODEL} | Langfuse session: {session_id}")
    print("  Type 'quit' to exit")
    print("=" * 60)

    turn = 0
    async with AsyncRAILClient(api_key=RAIL_API_KEY) as rail:
        while True:
            user_input = input("\nYou: ").strip()
            if not user_input or user_input.lower() in ("quit", "exit"):
                break

            turn += 1
            messages.append({"role": "user", "content": user_input})

            # Unique trace per turn — Langfuse groups them by session_id
            trace_id = f"{session_id}-turn-{turn}"

            # 1. Generate with OpenAI
            completion = await openai.chat.completions.create(
                model=MODEL,
                messages=messages,
            )
            response_text = completion.choices[0].message.content or ""
            messages.append({"role": "assistant", "content": response_text})

            # 2. Evaluate via RAIL + push scores to Langfuse
            context = "\n".join(
                f"{m['role']}: {m['content']}" for m in messages[-6:]
            )

            result = await rail_langfuse.evaluate_and_log(
                content=response_text,
                trace_id=trace_id,
                session_id=session_id,
                mode="basic",
                domain="healthcare",
                context=context,
            )

            # 3. Display
            print(f"\nAssistant: {response_text}")
            print(
                f"  [RAIL: {result.score:.1f}/10 | "
                f"confidence: {result.confidence:.2f} | "
                f"trace: {trace_id}]"
            )

            # Show dimension breakdown
            dims = result.dimension_scores
            if dims:
                for dim_name in sorted(dims.keys()):
                    dim_data = dims[dim_name]
                    dim_score = dim_data.get("score", 0) if isinstance(dim_data, dict) else dim_data
                    print(f"    {dim_name}: {dim_score}")

            # Warn on low scores
            if result.score < THRESHOLD:
                print(
                    f"  WARNING: Score {result.score:.1f} below threshold {THRESHOLD}. "
                    f"Check Langfuse trace {trace_id} for details."
                )

    print(f"\nSession complete. View traces in Langfuse under session: {session_id}")
    print("Goodbye!")


if __name__ == "__main__":
    asyncio.run(main())
